GET http://localhost:3000/employees

###
//getting emp by id
GET http://localhost:3000/employees/63219aff06791e096b62e7a1

###

POST http://localhost:3000/employees
Content-Type: application/json

{
    "name": "Adam Sandler",
    "job": "Actor"
}


###
PATCH  http://localhost:3000/employees/63219aff06791e096b62e7a1
Content-Type: application/json

{
    "name": "Ali Ahmed",
    "job": "manager"
}

###

DELETE http://localhost:3000/employees/63219aff06791e096b62e7a1