//getting all users
GET http://localhost:3030/users

###

//creating a new user
POST http://localhost:3030/emp
Content-Type: application/json

{
    "title" : "new book",
    "author" : "eddy",
    "age" : 23,
    "job" : "Engineer"
}
###

//getting one user
GET http://localhost:3030/users/
###
DELETE http://localhost:3030/users/
###

//updating a user
PATCH http://localhost:3030/users/63fb1d718c70b268f0d937ba 
Content-Type: application/json

{
    "job" : "Manager"
}
###

