//creating a new book
POST http://localhost:3030/books/new
Content-Type: application/json

{
    "name" : "Spider-man: no way home",
    "author" : "Marvel",
    "description" : "Peter's identity has been revealed",
    "price" : 29.99
}
###
//getting all users

GET http://localhost:3030/books
###

//getting one user
GET http://localhost:3030/books/
###

//updating a user
PATCH http://localhost:3030/books/ 
Content-Type: application/json

{
    "name" : "Oliver Twist",
    "author" : "Charles Dickens",
    "price" : 29.99
}
###
DELETE http://localhost:3030/books/
###

