//creating a new book
POST http://localhost:3030/books/new
Content-Type: application/json

{
    "name" : "Spider-man: hi home",
    "author" : "Marvel",
    "description" : "After returning from the snap.",
    "price" : 39.99,
    "image" : "cover.png",
    "available": true
}
###
//getting all users

GET http://localhost:3030/books
###

//getting one user
GET http://localhost:3030/books/
###

//updating a user
PATCH http://localhost:3030/books/63fc628ac0e71231d90ac5c5
Content-Type: application/json

{
    "available" : false
}
###
DELETE http://localhost:3030/books/63fc61cf7d9b5477e962a6bf
###

